version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: VIA_tabloid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7895
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/VIA_tabloid
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 7895

  

  frontend:
    build: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: