name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package
  
      - name: Run Tests with Maven
        run: mvn test --file ./backend/pom.xml  # Adjust path if your pom.xml is in a different location
  
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: backend/target/*.war  # Adjust based on your artifact output path
  
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: backend/target/surefire-reports  # Adjust based on your test results path
